USE madcamp_week2_db;

-- `Ballade`, `Dance`, `R&B`, `OST`, `Pop`, `Hiphop`
-- 5 6 3 4 1 2
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (1, "Ballade", "오래된 노래", "Huh Gak, 임한별, 이무진 및 이진성");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (2, "Ballade", "심(心)", "DK(디셈버)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (3, "Ballade", "Love wins all", "아이유");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (4, "Ballade", "헤어지자 말해요", "박재정");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (5, "Ballade", "사막에서 꽃을 피우듯", "우디 (Woody)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (6, "Ballade", "첫 키스에 내 심장은 120BPM", "경서");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (7, "Ballade", "청혼하지 않을 이유를 못 찾았어", "이무진");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (8, "Ballade", "사랑인가 봐", "멜로망스");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (9, "Ballade", "산책", "성시경");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (10, "Ballade", "다정히 내 이름을 부르면", "경서예지 및 전건호");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (11, "Ballade", "사랑하지 않아서 그랬어", "임한별");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (12, "Ballade", "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지", "악동뮤지션");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (13, "Ballade", "별의 하모니", "QWER");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (14, "Ballade", "잘 지내자, 우리 (여름날 우리 X 로이킴)", "로이킴");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (15, "Ballade", "이러지마 제발 (PLEASE DON'T…)", "케이윌(K.will)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (16, "Ballade", "그랬나봐", "유회승 (엔플라잉)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (17, "Ballade", "달빛에 그려지는", "미연");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (18, "Ballade", "너의 편이 돼 줄게", "다비치");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (19, "Ballade", "천상연", "이창섭");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (20, "Ballade", "다시 사랑한다면 (김필 Ver.)", "임영웅");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (21, "Ballade", "영원", "DK(디셈버)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (22, "Ballade", "그대가 내 안에 박혔다(그내박)", "순순희(기태)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (23, "Ballade", "나에게 그대만이", "탑현");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (24, "Ballade", "속는 셈 치고 다시 만나자", "케이시 (Kassy)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (25, "Ballade", "저녁 하늘", "에일리(Ailee)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (26, "Ballade", "물론", "허각");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (27, "Ballade", "늦은 밤 너의 집 앞 골목길에서", "노을");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (28, "Ballade", "곰인형", "린");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (29, "Ballade", "내게 어울릴 이별 노래가 없어 (Prod. 윤상)", "케이윌");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (30, "Ballade", "꿈", "태연");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (31, "Ballade", "그랬나봐", "김형중");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (32, "Ballade", "기억을 걷는 시간", "넬 (Nell)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (33, "Ballade", "널 미워하기로 했어", "이예준");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (34, "Ballade", "취기를 빌려 (취향저격 그녀 X 산들)", "산들(B1A4)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (35, "Ballade", "나무", "카더가든");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (36, "Ballade", "응급실", "izi");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (37, "Ballade", "미치게 그리워서", "안세하");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (38, "Ballade", "사랑..그게 뭔데", "지아");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (39, "Ballade", "Monologue", "테이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (40, "Ballade", "슬픈 초대장", "순순희 (지환)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (41, "Ballade", "취중고백", "김민석");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (42, "Ballade", "일과 이분의 일", "츄 (이달의 소녀)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (43, "Ballade", "I got lucky(운이 좋았지)", "Kwon Jin Ah(권진아)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (44, "Ballade", "하늘바라기 (feat. 하림)", "정은지");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (45, "Ballade", "그대가 내 안에 박혔다", "황치열");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (46, "Ballade", "새벽에 걸려온 너의 전화는", "한동근");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (47, "Ballade", "내가 아니라도", "주호");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (48, "Ballade", "No Matter Where", "엠씨더맥스");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (49, "Ballade", "너에게 쓰는 편지 (feat. 린)", "MC 몽");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (50, "Ballade", "비가 오는 날엔", "비스트");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (51, "Dance", "Supernova", "aespa");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (52, "Dance", "고민중독", "QWER");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (53, "Dance", "Boom Boom Bass", "RIIZE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (54, "Dance", "해야 (HEYA)", "IVE (아이브)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (55, "Dance", "Right Now", "NewJeans");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (56, "Dance", "ABCD", "NAYEON");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (57, "Dance", "첫 만남은 계획대로 되지 않아", "TWS");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (58, "Dance", "홀씨", "아이유");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (59, "Dance", "Girls Never Die", "tripleS (트리플에스)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (60, "Dance", "Midas Touch", "KISS OF LIFE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (61, "Dance", "DASH", "NMIXX");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (62, "Dance", "Perfect Night", "LE SSERAFIM");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (63, "Dance", "Devil by the Window", "TOMORROW X TOGETHER");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (64, "Dance", "Cosmic", "Red Velvet");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (65, "Dance", "ERROR 405", "JD1");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (66, "Dance", "오르트구름", "윤하 (YOUNHA)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (67, "Dance", "손오공", "SEVENTEEN");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (68, "Dance", "U & I", "에일리(Ailee)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (69, "Dance", "건물 사이에 피어난 장미", "H1-KEY");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (70, "Dance", "Tally", "BLACKPINK");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (71, "Dance", "Lips (feat. 지젤 of aespa)", "BOL4");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (72, "Dance", "Dynamite", "BTS (방탄소년단)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (73, "Dance", "Strawberry Rush", "츄 (CHUU)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (74, "Dance", "Weekend", "태연 (TAEYEON)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (75, "Dance", "어젯밤 (Guitar by 박주원)", "정한x원우");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (76, "Dance", "Earth, Wind & Fire", "BOYNEXTDOOR");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (77, "Dance", "Standing Next to You", "정국 (Jung Kook)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (78, "Dance", "What is Love?", "TWICE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (79, "Dance", "WANNABE", "ITZY");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (80, "Dance", "비행기", "거북이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (81, "Dance", "Stay This Way", "fromis_9");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (82, "Dance", "Teddy Bear", "STAYC(스테이씨)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (83, "Dance", "삐딱하게 (Crooked)", "지드래곤(G-DRAGON)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (84, "Dance", "예술이야", "싸이(PSY)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (85, "Dance", "붉은 노을", "BIGBANG");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (86, "Dance", "Panorama", "IZ*ONE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (87, "Dance", "Dun Dun Dance", "오마이걸 (OH MY GIRL)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (88, "Dance", "다시 여기 바닷가", "싹쓰리 (유두래곤&린다G&비룡)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (89, "Dance", "Blue Moon", "엔플라잉 (N.Flying)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (90, "Dance", "I'm Ready", "청하");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (91, "Dance", "주문-MIROTIC", "TVXQ!");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (92, "Dance", "WORK", "ATEEZ (에이티즈)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (93, "Dance", "SMILEY (feat. BIBI)", "YENA (최예나)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (94, "Dance", "Lollipop (Bigbang)", "2NE1");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (95, "Dance", "HER", "블락비(Block B)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (96, "Dance", "BADVILLAIN", "BADVILLAIN (배드빌런)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (97, "Dance", "View", "SHINee");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (98, "Dance", "LOVING U (러빙유)", "씨스타(Sistar)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (99, "Dance", "STEP", "카라");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (100, "Dance", "Change", "(G)I-DLE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (101, "R&B", "동창회 MEGA MIX (feat. Cha jinhyuck, MOYO, Yyeon, Kang hankook)", "타임피버");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (102, "R&B", "By Your Side", "Crush");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (103, "R&B", "Love Lee", "AKMU");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (104, "R&B", "Square (2017)", "Yerin Baek");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (105, "R&B", "Trip (feat. 한나)", "릴러말즈(Leellamarz)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (106, "R&B", "Every Night", "Paul Blanco");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (107, "R&B", "All I Wanna Do (Korean Version) (feat. Hoody, Loco)", "Jay Park");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (108, "R&B", "벌써 일년", "브라운 아이즈");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (109, "R&B", "D (Half Moon) (feat. 개코)", "DEAN");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (110, "R&B", "별이될께", "디셈버(December)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (111, "R&B", "Impurities", "LE SSERAFIM");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (112, "R&B", "비도 오고 그래서 You, Clouds, Rain (feat. Shin Yong Jae)", "Heize");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (113, "R&B", "Pink cheeks", "Eldon");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (114, "R&B", "No Make Up", "Zion.T");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (115, "R&B", "Thursday Night(목요일 밤) (feat. Beenzino)", "URBAN ZAKAPA(어반자카파)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (116, "R&B", "바람기억", "나얼");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (117, "R&B", "Nerdy Love (feat. 백예린 Yerin Baek)", "pH-1");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (118, "R&B", "Can I Love? (feat. 유라)", "Cosmic Boy");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (119, "R&B", "비", "폴킴");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (120, "R&B", "Hate You", "정국 (Jung Kook)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (121, "R&B", "Chi-Ka (feat. DEAN)", "Tabber");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (122, "R&B", "RIDE (feat. 따마)", "SOLE (쏠)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (123, "R&B", "와르르 ♥", "콜드");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (124, "R&B", "달", "스트레이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (125, "R&B", "대충 입고 나와", "우디 (Woody)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (126, "R&B", "비 오는 날 듣기 좋은 노래 (feat. Colde)", "Epik High");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (127, "R&B", "PILLOW", "PL");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (128, "R&B", "한숨(Breathe)", "이하이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (129, "R&B", "가슴 시린 이야기 (Rap Feat. 용준형 of BEAST)", "휘성 Wheesung");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (130, "R&B", "연(捐)(Year)", "BIGMAMA");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (131, "R&B", "언제나 사랑해", "DK");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (132, "R&B", "잘 된 일이야", "나비(NAVI)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (133, "R&B", "춤", "dori");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (134, "R&B", "긴 꿈 (feat. 이하이)", "B.I");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (135, "R&B", "Thought Of You(네 생각)", "John Park(존박)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (136, "R&B", "3 2 1", "JAEHA");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (137, "R&B", "이제 우리 꿈에서만 만나", "Yyeon");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (138, "R&B", "WINE(오늘 취하면) (Prod. SUGA) (feat. Changmo)", "SURAN(수란)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (139, "R&B", "사장님 도박은 재미로 하셔야 합니다", "비비(BIBI)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (140, "R&B", "let's go picnic", "죠지");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (141, "R&B", "Ordinary Days", "D.O.");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (142, "R&B", "긴 밤", "Seori");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (143, "R&B", "마음대로", "콜드");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (144, "R&B", "미련한 사랑", "JK김동욱");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (145, "R&B", "O (feat. 이하이)", "코드 쿤스트(CODE KUNST)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (146, "R&B", "I Remember", "ASH ISLAND");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (147, "R&B", "언제나 사랑해", "제이세라");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (148, "R&B", "내가 그댈", "세븐 데이즈");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (149, "R&B", "천재는 시발 새끼들한테 미움받아 단명한다", "Ruru");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (150, "R&B", "Nevertheless", "Peder Elias");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (151, "OST", "Everytime", "첸(CHEN) 및 펀치(Punch)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (152, "OST", "Whisky on the Rock", "김연지");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (153, "OST", "위로 Consolation", "권진아");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (154, "OST", "Shallow", "Lady Gaga 및 브래들리 쿠퍼");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (155, "OST", "Stayed Gone", "Andrew Underberg, Sam Haft, Christian Borle, Amir Talai 및 Joel Perez");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (156, "OST", "Love Is an Open Door (From 'Frozen'/Soundtrack Version)", "Kristen Bell 및 Santino Fontana");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (157, "OST", "Rambley Review (feat. OtterBoyVA)", "RecD 및 Jakeneutron");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (158, "OST", "Do You Hear The People Sing?", "Aaron Tveit, Eddie Redmayne, Students 및 Les Misérables Cast");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (159, "OST", "I'II be your star(넌 내게 특별하고)", "So Soo Bin(소수빈)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (160, "OST", "Loser, Baby", "Keith David, Blake Roman, Andrew Underberg 및 Sam Haft");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (161, "OST", "레베카 Act. 2 옥주현, 임혜영 Version", "옥주현 및 임혜영");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (162, "OST", "너의 꿈속에서", "카이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (163, "OST", "Hell Is Forever", "Andrew Underberg, Sam Haft, Alex Brightman 및 Erika Henningsen");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (164, "OST", "헤어지는 중 입니다 (불광동 휘발유)", "김연지");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (165, "OST", "City Of Stars (From 'La La Land' Soundtrack)", "Ryan Gosling 및 Emma Stone");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (166, "OST", "향기 Scent", "샘김");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (167, "OST", "사랑이란", "정문성 및 전미도");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (168, "OST", "바다아이", "윤하(Younha)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (169, "OST", "Way Back Into Love", "Hugh Grant 및 Haley Bennett");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (170, "OST", "한사람", "허각");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (171, "OST", "뮤지컬 '지킬앤하이드' 2021 Korean Cast Recording - This is the Moment", "홍광호");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (172, "OST", "The Amazing Digital Circus Theme Song", "Carameii");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (173, "OST", "운명을 거슬러", "SG워너비 및 김종욱");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (174, "OST", "시청 앞 지하철 역에서", "Kwak jineon");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (175, "OST", "너는 기억한다", "폴킴");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (176, "OST", "태극기 휘날리며 에필로그", "이동준");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (177, "OST", "One Day More", "Les Misérables Cast");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (178, "OST", "Pure Imagination (from 'Wonka')", "Timothée Chalamet");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (179, "OST", "Fixer Upper (From 'Frozen'/Soundtrack Version)", "Maia Wilson 및 Cast of Frozen");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (180, "OST", "바본가봐", "아이비");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (181, "OST", "Hopes And Dreams", "Toby Fox");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (182, "OST", "Pacific Rim (feat. Tom Morello)", "Ramin Djawadi 및 Tom Morello");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (183, "OST", "Arabian Nights (2019)", "Will Smith");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (184, "OST", "Going The Distance (From 'Rocky' Soundtrack / Remastered 2006)", "Bill Conti");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (185, "OST", "난 괴물", "카이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (186, "OST", "Time", "Hans Zimmer");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (187, "OST", "황금별", "신영숙");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (188, "OST", "Red Alert 3 Theme - Soviet March", "James Hannigan");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (189, "OST", "SOMETIMES(가끔)", "ZIA(지아)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (190, "OST", "단 하나의 미래", "유준상, 박은태 및 프랑켄슈타인 앙상블");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (191, "OST", "He's a Pirate", "Klaus Badelt");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (192, "OST", "Defying Gravity (From 'Wicked' Original Broadway Cast Recording/2003)", "Kristin Chenoweth 및 Idina Menzel");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (193, "OST", "The Windmills of your Mind (From The Thomas Crown Affair / De L'Affaire Thomas Crown)", "Chad Lawson");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (194, "OST", "Finale", "Andrew Underberg, Sam Haft, Erika Henningsen, Jeremy Jordan, Amir Talai, Stephanie Beatriz, Blake Roman, Keith David, Christian Borle, Joel Perez, Kimiko Glenn 및 Krystina Alabado");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (195, "OST", "A Lovely Night", "Ryan Gosling 및 Emma Stone");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (196, "OST", "애태우나요", "규현 (KYUHYUN)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (197, "OST", "Extras", "Molly Daisy Scarpine 및 Arc System Works");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (198, "OST", "More Than Anything", "Andrew Underberg, Sam Haft, Jeremy Jordan 및 Erika Henningsen");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (199, "OST", "I Dreamed A Dream (From 'Les Misérables')", "Anne Hathaway");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (200, "OST", "Married Life", "Michael Giacchino");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (201, "Pop", "Bad", "Christopher");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (202, "Pop", "Steal The Show (From 'Elemental')", "Lauv");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (203, "Pop", "Dangerously", "Charlie Puth");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (204, "Pop", "pocket locket", "Alaina Castillo");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (205, "Pop", "These Tears", "Andy Grammer");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (206, "Pop", "2002", "Anne-Marie");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (207, "Pop", "Memories", "Maroon 5");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (208, "Pop", "Shape of You", "Ed Sheeran");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (209, "Pop", "Ghost Town", "Benson Boone");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (210, "Pop", "There's Nothing Holdin' Me Back", "Shawn Mendes");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (211, "Pop", "What Makes You Beautiful", "One Direction");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (212, "Pop", "If We Ever Broke Up", "Mae Stephens");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (213, "Pop", "I'm Not The Only One", "Sam Smith");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (214, "Pop", "we can't be friends (wait for your love)", "Ariana Grande");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (215, "Pop", "Love Yourself", "Justin Bieber");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (216, "Pop", "Jingle Bell Rock", "Bobby Helms");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (217, "Pop", "Loving You Girl (feat. Hkeem)", "Peder Elias");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (218, "Pop", "12:45 (Stripped)", "Etham");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (219, "Pop", "Blank Space", "Taylor Swift");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (220, "Pop", "Uptown Funk (feat. Bruno Mars)", "Mark Ronson");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (221, "Pop", "bad guy", "Billie Eilish");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (222, "Pop", "Flowers", "Miley Cyrus");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (223, "Pop", "Symphony (feat. Zara Larsson)", "Clean Bandit");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (224, "Pop", "Someone You Loved", "Lewis Capaldi");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (225, "Pop", "Unholy", "Sam Smith 및 Kim Petras");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (226, "Pop", "YOUTH", "Troye Sivan");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (227, "Pop", "Call Me Maybe", "Carly Rae Jepsen");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (228, "Pop", "Stronger (What Doesn't Kill You)", "Kelly Clarkson");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (229, "Pop", "I'm Yours", "Jason Mraz");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (230, "Pop", "Me Too", "Meghan Trainor");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (231, "Pop", "I Like You (A Happier Song) (feat. Doja Cat)", "Post Malone");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (232, "Pop", "drunk text", "Henry Moodie");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (233, "Pop", "a thousand years", "Christina Perri");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (234, "Pop", "Rolling in the Deep", "Adele");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (235, "Pop", "Lose My Breath (feat. Charlie Puth)", "Stray Kids");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (236, "Pop", "Watermelon Sugar", "Harry Styles");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (237, "Pop", "Billie Jean", "Michael Jackson");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (238, "Pop", "7 Years", "Lukas Graham");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (239, "Pop", "abcdefu", "GAYLE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (240, "Pop", "CHRISTIAN", "Zior Park");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (241, "Pop", "No One Else Like You", "Adam Levine");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (242, "Pop", "Nonsense", "Sabrina Carpenter");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (243, "Pop", "Stereo Hearts (feat. Adam Levine)", "Gym Class Heroes");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (244, "Pop", "Kings & Queens", "Ava Max");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (245, "Pop", "Training Season", "Dua Lipa");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (246, "Pop", "High", "5 Seconds of Summer");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (247, "Pop", "Cake By The Ocean", "DNCE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (248, "Pop", "Leave Before You Love Me", "Marshmello 및 Jonas Brothers");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (249, "Pop", "Me And My Broken Heart", "Rixton");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (250, "Pop", "메리 메리 크리스마스", "이석훈, 윤하 (YOUNHA), CIX (씨아이엑스) 및 cignature (시그니처)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (251, "Hiphop", "SPOT! (feat. JENNIE)", "ZICO");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (252, "Hiphop", "MILLION DOLLAR BABY", "Tommy Richman");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (253, "Hiphop", "F*ck My Life", "SEVENTEEN");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (254, "Hiphop", "Houdini", "Eminem");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (255, "Hiphop", "Officially Missing You", "긱스 (Geeks)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (256, "Hiphop", "NOT SORRY (Prod. by Slom) (feat. pH-1)", "이영지");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (257, "Hiphop", "리무진 (Prod. GRAY) (feat. MINO (송민호))", "BE'O");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (258, "Hiphop", "Not Like Us", "Kendrick Lamar");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (259, "Hiphop", "만남은 쉽고 이별은 어려워 (Prod. TOIL) (feat. 릴러말즈 (Leellamarz))", "베이식");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (260, "Hiphop", "검정색하트 (feat. Leellamarz, BE'O)", "TOIL");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (261, "Hiphop", "INDUSTRY BABY", "Lil Nas X 및 Jack Harlow");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (262, "Hiphop", "Achoo (Prod. GroovyRoom) (feat. pH-1, 김하온 (HAON), 그루비룸 (GroovyRoom))", "미란이 (MIRANI)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (263, "Hiphop", "Missing You ft. 김윤아 of 자우림 (feat. 김윤아 of 자우림)", "G-DRAGON");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (264, "Hiphop", "처음 마주쳤을 때처럼", "TOIL 및 Gist");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (265, "Hiphop", "Stay With Me (feat. Skinny Brown)", "ASH ISLAND");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (266, "Hiphop", "I'll Be Missing You (feat. Faith Evans, 112)", "P. Diddy");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (267, "Hiphop", "Oasis (feat. 지코 (ZICO))", "Crush");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (268, "Hiphop", "BAND4BAND", "Central Cee 및 Lil Baby");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (269, "Hiphop", "두사랑 (feat. Mad Clown)", "DAVICHI");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (270, "Hiphop", "Because You're Pretty(예쁘잖아)", "GIRIBOY(기리보이)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (271, "Hiphop", "HUMBLE.", "Kendrick Lamar");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (272, "Hiphop", "씨스루 (feat. Zion.T, 개코, Gaeko Of Dynamicduo)", "프라이머리");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (273, "Hiphop", "아이스크림", "MC 몽");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (274, "Hiphop", "Text Me", "DPR LIVE");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (275, "Hiphop", "CARNIVAL", "¥$, Kanye West, Ty Dolla $ign 및 Rich The Kid");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (276, "Hiphop", "Young, Wild & Free (feat. Bruno Mars)", "Wiz Khalifa 및 Snoop Dogg");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (277, "Hiphop", "Domodachi (feat. Little Simz)", "RM 및 Little Simz");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (278, "Hiphop", "감동이야 (feat. SUNG SI KYUNG, 성시경)", "싸이");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (279, "Hiphop", "Empire State Of Mind (feat. Alicia Keys)", "JAY-Z");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (280, "Hiphop", "FE!N (feat. Playboi Carti)", "Travis Scott");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (281, "Hiphop", "Jimmy Cooks (feat. 21 Savage)", "Drake");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (282, "Hiphop", "Café", "BIGBANG");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (283, "Hiphop", "พี่ชอบหนูที่สุดเลย (I Like You The Most) Feat.VARINZ (feat. VARINZ)", "PONCHET");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (284, "Hiphop", "Like That", "Future, Metro Boomin 및 Kendrick Lamar");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (285, "Hiphop", "WAP (feat. 메건 더 스탤리언)", "Cardi B(카디 비)");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (286, "Hiphop", "Limbo", "Freddie Dredd");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (287, "Hiphop", "역겹겠지만", "B.I");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (288, "Hiphop", "Taste (feat. Offset)", "Tyga");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (289, "Hiphop", "Word to the Wise", "Matt Corman");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (290, "Hiphop", "Still D.R.E. (feat. Snoop Dogg)", "Dr. Dre");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (291, "Hiphop", "Misfits (feat. MELOH, Kid Wine)", "Skinny Brown");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (292, "Hiphop", "See You Again (feat. Kali Uchis)", "Tyler, The Creator");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (293, "Hiphop", "Low (feat. T-Pain)", "Flo Rida");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (294, "Hiphop", "Surround Sound (feat. 21 Savage, Baby Tate)", "JID");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (295, "Hiphop", "Right away (feat. pH-1)", "쿠기");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (296, "Hiphop", "In Da Club", "50 Cent");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (297, "Hiphop", "Best Friend (feat. Doja Cat)", "Saweetie");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (298, "Hiphop", "20 Min", "Lil Uzi Vert");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (299, "Hiphop", "Sprinter", "Dave 및 Central Cee");
INSERT INTO MUSIC(id, genre, music_name, artist) VALUES (300, "Hiphop", "Praise The Lord (Da Shine) (feat. Skepta)", "A$AP Rocky");